- name: Copy artifact.tar.gz
  copy:
    src: "artifact.tar.gz"
    dest: "/home/ubuntu/artifact.tar.gz"

- name: Executing node
  shell: |
    cd /home/ubuntu/
    tar -xvf artifact.tar.gz
    npm install
    pm2 stop default
    pm2 start npm -- start
