Description: >
  Cloudfront distribution for Onlinesafety App.

Parameters:
  WorkflowID:
    Description: |
      Unique identifier used in s3 was bayurzx (onlinesafety-bayurzx)
      Simply run : 
        aws cloudformation deploy \
         --template-file .circleci/files/cloudfront.yml \
         --stack-name InitialStack \
         --parameter-overrides WorkflowID=onlinesafety-bayurzx

    Type: String

  AcmCertificateArn:
    Description: |
      AWS Certiifcate Manager ARN to use for our cloudfornt distribution

    Type: String


Resources:
  
  CloudFrontOriginAccessIdentity:
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Origin Access Identity for Serverless Static Website

  WebpageCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        # we add SSL/TLS certiificate here
        ViewerCertificate:
          # AcmCertificateArn: "arn:aws:acm:us-east-1:123456789012:certificate/12345678-1234-1234-1234-123456789012"
          AcmCertificateArn: !Sub "${AcmCertificateArn}"
          SslSupportMethod: sni-only
        Origins:
          - DomainName: !Sub "onlinesafety-${WorkflowID}.s3.amazonaws.com"
            Id: webpage
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"
        Enabled: True
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: False
          TargetOriginId: webpage
          ViewerProtocolPolicy: redirect-to-https

Outputs:
  WorkflowID:
    Value: !Sub ${WorkflowID}
    Description: URL for website hosted on S3
    Export:
      Name: WorkflowID

  AcmCertificateArn:
    Value: !Sub ${AcmCertificateArn}
    Description: The certificate ARN I created
    Export:
      Name: AcmCertificateArn
