import Head from 'next/head'
// import '../styles/Game.css'
import Game from "../components/Game";


export default function Home() {
  return (
    <div>
      <Head>
        <title>Online Safety Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <Game />
    </div>
  )
}
